### PR TITLE
Sustyle

### PR DESCRIPTION
**Pull request by mricanho**
This is Sustyle, the website focused on the latest sustainability articles. Articles are separated into four main categories. This web page allows the registration of new users and authenticates them, users can create articles and assign them a category, they can also vote for the articles they like the most.

This site has been created mainly with Ruby on Rails as a framework and PostgreSQL database.

The User Interface specifications for this project are:

The project is a desktop web app.
App validates all user input
The app is an MVP of the full product (with the full graphical design but only basic features that can be easily extended in the future)
The project is deployed and accessible online here: https://tennix-sports-blog.herokuapp.com/
The user logs in to the app, only by typing the username (a proper authenticated login is not a requirement)
The user is presented with the homepage that includes:
Featured article with full-width image and title in the first row. This should be an article with the biggest number of votes.
List of all categories in order of priority. Each category should be displayed as a square with its name on the top and its most recent article's title in the bottom. The background image should be the image of the most recent article in this category.
When the user clicks the category name they can see all articles in that category:
Articles are sorted by most recent.
Each article displays: image, title, truncated text as preview and its author name.
Add extra button to add a vote for article (each user can vote only once).
Each page should use the same top menu and footer:
Top menu is presented at the Homepage sketch. It should include only links to pages that are implemented.
Footer is presented at the Articles in selected category page sketch.
When user opens "Write an article" page:
A form with all necessary fields is displayed.
Technical features of the project:

Use Active Storage and Cloudinary for users uploaded images
If an image is not provided, a random image from Unsplash is taken
Use RESTFUL routes
Use controllers to intercept user requests
Use view templates for HTML with embedded data
Use assets pipeline
Connect Database to app
Use Active Record as ORM
Use Active Record associations to model real life system (based on Database schema)
Use Active Record queries to translate app requirements to SQL queries
Use ActiveRecord validations
Pass user input from view through controller to model in a safe way
Use thin controllers and distinguish between logic and presentation tiers
Avoid n+1 queries problem
Use unit tests (Rspec)
Use ActiveRecord validations

### CODE REVIEW

**Comment by mricanho** [comment]
Just an update!

I have a super problem with Heroku, I'm working hard to solve it, but I guess that I'm gonna need a few hours to figure it out because Heroku is #pain 😭 .

Thanks for reading me! Greetings!

**Comment by mricanho** [comment]
Update #2 

Heroku problem resolved was the bundler version! 🤕

**Comment by LamiaSristy** [comment]
## Hello @mricanho, please don't add any other updates, as this project is now under review process.

**Comment by mricanho** [comment]
🛑 IMPORTANT 🛑 

So, the proper installation is showed in the README file, but I made I video cloning my repository and explaining why you need to install the repository following the instructions. Basically, it's a problem because I downgrade the Bundler to properly deployment on Heroku, so that causes conflicts with Action Text and prevents the render of the website on the RSpec tests. If you follow the instructions you will not have any problem! 

[TUTORIAL VIDEO](https://www.loom.com/share/22d0454fa3004889abf1e6d1255d062a)

Have an excellent day!

**Pull request merged**
